//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPatterns.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroHungerEntities : DbContext
    {
        public ZeroHungerEntities()
            : base("name=ZeroHungerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<CollectRequest> CollectRequests { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<FoodDetail> FoodDetails { get; set; }
        public DbSet<NGO> NGOs { get; set; }
        public DbSet<Restaurant> Restaurants { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
