//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepoWithValidations.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.MedicineSuppliers = new HashSet<MedicineSupplier>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<MedicineSupplier> MedicineSuppliers { get; set; }
    }
}
